"""Agent-facing helpers for deterministic action IDs and observations."""

from __future__ import annotations

import json
import operator
from collections.abc import Mapping
from typing import Any

from sts2sim.api import legal_actions as _legal_actions
from sts2sim.api import serialize as _serialize
from sts2sim.engine.models import Action, ActionType, RunPhase

DEFAULT_MAX_ACTIONS = 512

ACTION_TYPE_IDS: dict[str, int] = {
    action_type.value: index for index, action_type in enumerate(ActionType)
}
PHASE_IDS: dict[str, int] = {phase.value: index for index, phase in enumerate(RunPhase)}

OBSERVATION_VECTOR_SCHEMA: tuple[str, ...] = (
    "phase_id",
    "act",
    "floor",
    "ascension",
    "player_hp",
    "player_max_hp",
    "player_block",
    "player_energy",
    "player_max_energy",
    "player_stars",
    "player_resource_total",
    "player_gold",
    "master_deck_count",
    "relic_count",
    "curse_count",
    "potion_count",
    "legal_action_count",
    "combat_turn",
    "combat_hand_count",
    "combat_draw_pile_count",
    "combat_discard_pile_count",
    "combat_exhaust_pile_count",
    "combat_orb_count",
    "combat_orb_slots",
    "combat_orb_value_total",
    "alive_monster_count",
    "monster_hp_total",
    "monster_block_total",
    "incoming_damage",
    "map_node_count",
    "map_edge_count",
    "map_completed_count",
    "reward_gold",
    "reward_card_count",
    "reward_relic_count",
    "reward_potion_count",
)


def action_space(state: Any) -> list[dict[str, Any]]:
    """Return state-local action descriptors with deterministic integer IDs.

    IDs are assigned after sorting legal engine actions by their canonical JSON
    payload. They are stable for equivalent states, but intentionally local to
    the state because card instance IDs, map nodes, and reward targets are
    generated by the simulator.
    """

    return [
        _action_descriptor(action_id, action)
        for action_id, action in enumerate(_ordered_legal_actions(state))
    ]


def action_mask(state: Any, *, max_actions: int | None = None) -> tuple[int, ...]:
    """Return a binary mask for legal action IDs.

    With ``max_actions=None`` the mask length matches the state-local action
    space, so every entry is legal. Pass ``max_actions`` to get a fixed-width
    mask padded with zeros for Gymnasium-style discrete policies.
    """

    action_count = len(_ordered_legal_actions(state))
    if max_actions is None:
        return tuple(1 for _ in range(action_count))
    if max_actions < 0:
        raise ValueError("max_actions must be non-negative")
    if action_count > max_actions:
        raise ValueError(
            f"state has {action_count} legal actions, which exceeds max_actions={max_actions}"
        )
    return tuple(1 if index < action_count else 0 for index in range(max_actions))


def decode_action(state: Any, action_id: int) -> Action:
    """Map a deterministic state-local action ID back to an engine ``Action``."""

    if isinstance(action_id, bool):
        raise TypeError("action_id must be an integer, not bool")
    action_index = operator.index(action_id)
    if action_index < 0:
        raise IndexError(f"action_id {action_id} is not legal for this state")
    actions = _ordered_legal_actions(state)
    try:
        return actions[action_index]
    except IndexError as exc:
        raise IndexError(f"action_id {action_id} is not legal for this state") from exc


def encode_observation(state: Any, *, include_state: bool = True) -> dict[str, Any]:
    """Encode a simulator state as a JSON-friendly observation payload.

    The ``vector`` field is fixed-length and numeric. Structured sections keep
    useful symbolic context available for agents that are not purely tensor
    based. The full serialized state is included by default for lossless
    debugging and can be omitted with ``include_state=False``.
    """

    payload = _serialize(state)
    phase = str(payload.get("phase", ""))
    legal_action_count = len(_ordered_legal_actions(state))

    player = _mapping(payload.get("player"))
    combat = _mapping(payload.get("combat"))
    game_map = _mapping(payload.get("map"))
    reward = _mapping(payload.get("reward"))

    monsters = _sequence(combat.get("monsters"))
    alive_monsters = [
        monster for monster in monsters if _number(_mapping(monster).get("hp")) > 0
    ]

    resources = _mapping(player.get("resources"))
    player_summary = {
        "hp": _int(player.get("hp")),
        "max_hp": _int(player.get("max_hp")),
        "block": _int(player.get("block")),
        "energy": _int(player.get("energy")),
        "max_energy": _int(player.get("max_energy")),
        "stars": _int(resources.get("star", resources.get("stars", 0))),
        "resource_total": sum(_int(value) for value in resources.values()),
        "gold": _int(player.get("gold")),
        "resources": dict(resources),
    }
    counts = {
        "master_deck": len(_sequence(payload.get("master_deck"))),
        "relics": len(_sequence(payload.get("relics"))),
        "curses": len(_sequence(payload.get("curses"))),
        "potions": len(_sequence(payload.get("potions"))),
        "legal_actions": legal_action_count,
    }
    combat_summary = {
        "turn": _int(combat.get("turn")),
        "hand_count": len(_sequence(combat.get("hand"))),
        "draw_pile_count": len(_sequence(combat.get("draw_pile"))),
        "discard_pile_count": len(_sequence(combat.get("discard_pile"))),
        "exhaust_pile_count": len(_sequence(combat.get("exhaust_pile"))),
        "orb_count": len(_sequence(combat.get("orbs"))),
        "orb_slots": _int(combat.get("orb_slots")),
        "orb_value_total": sum(
            _int(_mapping(orb).get("value")) for orb in _sequence(combat.get("orbs"))
        ),
        "monster_count": len(monsters),
        "alive_monster_count": len(alive_monsters),
        "monster_hp_total": sum(_int(_mapping(monster).get("hp")) for monster in monsters),
        "monster_block_total": sum(
            _int(_mapping(monster).get("block")) for monster in monsters
        ),
        "incoming_damage": sum(
            _int(_mapping(monster).get("intent_damage")) for monster in alive_monsters
        ),
    }
    map_summary = {
        "node_count": len(_sequence(game_map.get("nodes"))),
        "edge_count": len(_sequence(game_map.get("edges"))),
        "completed_count": len(_sequence(game_map.get("completed_node_ids"))),
    }
    reward_summary = {
        "gold": _int(reward.get("gold")),
        "card_count": len(_sequence(reward.get("card_options")))
        + len(_sequence(reward.get("card_ids"))),
        "relic_count": int(bool(reward.get("relic_id")))
        + len(_sequence(reward.get("relic_ids"))),
        "potion_count": int(bool(reward.get("potion_id")))
        + len(_sequence(reward.get("potion_ids"))),
    }

    vector = [
        _float(PHASE_IDS.get(phase, -1)),
        _float(payload.get("act")),
        _float(payload.get("floor")),
        _float(payload.get("ascension")),
        _float(player_summary["hp"]),
        _float(player_summary["max_hp"]),
        _float(player_summary["block"]),
        _float(player_summary["energy"]),
        _float(player_summary["max_energy"]),
        _float(player_summary["stars"]),
        _float(player_summary["resource_total"]),
        _float(player_summary["gold"]),
        _float(counts["master_deck"]),
        _float(counts["relics"]),
        _float(counts["curses"]),
        _float(counts["potions"]),
        _float(counts["legal_actions"]),
        _float(combat_summary["turn"]),
        _float(combat_summary["hand_count"]),
        _float(combat_summary["draw_pile_count"]),
        _float(combat_summary["discard_pile_count"]),
        _float(combat_summary["exhaust_pile_count"]),
        _float(combat_summary["orb_count"]),
        _float(combat_summary["orb_slots"]),
        _float(combat_summary["orb_value_total"]),
        _float(combat_summary["alive_monster_count"]),
        _float(combat_summary["monster_hp_total"]),
        _float(combat_summary["monster_block_total"]),
        _float(combat_summary["incoming_damage"]),
        _float(map_summary["node_count"]),
        _float(map_summary["edge_count"]),
        _float(map_summary["completed_count"]),
        _float(reward_summary["gold"]),
        _float(reward_summary["card_count"]),
        _float(reward_summary["relic_count"]),
        _float(reward_summary["potion_count"]),
    ]

    observation: dict[str, Any] = {
        "schema_version": _int(payload.get("schema_version")),
        "phase": phase,
        "phase_id": PHASE_IDS.get(phase, -1),
        "vector_schema": list(OBSERVATION_VECTOR_SCHEMA),
        "vector": vector,
        "player": player_summary,
        "counts": counts,
        "combat": combat_summary,
        "map": map_summary,
        "reward": reward_summary,
        "legal_actions": {
            "count": legal_action_count,
            "ids": [descriptor["id"] for descriptor in action_space(state)],
        },
    }
    if include_state:
        observation["state"] = payload
    return observation


def _ordered_legal_actions(state: Any) -> tuple[Action, ...]:
    keyed_actions = [
        (_action_key(action), index, action)
        for index, action in enumerate(_legal_actions(state))
    ]
    return tuple(action for _key, _index, action in sorted(keyed_actions))


def _action_descriptor(action_id: int, action: Action) -> dict[str, Any]:
    payload = _action_payload(action)
    return {
        "id": action_id,
        "key": _canonical_json(payload),
        "type": str(payload["type"]),
        "action_type_id": ACTION_TYPE_IDS.get(str(payload["type"]), -1),
        "card_instance_id": payload.get("card_instance_id"),
        "target_id": payload.get("target_id"),
        "payload": dict(_mapping(payload.get("payload"))),
        "action": payload,
    }


def _action_key(action: Action) -> str:
    return _canonical_json(_action_payload(action))


def _action_payload(action: Action | Mapping[str, Any]) -> dict[str, Any]:
    if isinstance(action, Action):
        return dict(action.model_dump(mode="json", exclude_none=True))
    return dict(Action.model_validate(dict(action)).model_dump(mode="json", exclude_none=True))


def _canonical_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def _mapping(value: Any) -> Mapping[str, Any]:
    if isinstance(value, Mapping):
        return value
    return {}


def _sequence(value: Any) -> tuple[Any, ...]:
    if isinstance(value, (str, bytes, bytearray)) or value is None:
        return ()
    if isinstance(value, Mapping):
        return ()
    try:
        return tuple(value)
    except TypeError:
        return ()


def _number(value: Any) -> float:
    if isinstance(value, bool):
        return float(int(value))
    if isinstance(value, int | float):
        return float(value)
    return 0.0


def _int(value: Any) -> int:
    return int(_number(value))


def _float(value: Any) -> float:
    return float(_number(value))
